site_name: WEB MINING 2019
theme: material
nav :
- Home : pendahuluan1.md
- Web Content Mining :
    - Crawling : crawling.md
    - Preprocessing : prepro.md
    - VSM : vsm.md
    - TF-IDF : tfidf.md
    - Seleksi Fitur : fitur.md
    - Clustering : clustering.md
    - Kesimpulan : akhir.md 
- Web Structure Mining :
    - Crawl Link : crawl_link.md
    - PageRank : pagerank.md
    - Graph : graph.md